name: Build gir2swift and build SwiftGtk

# Dependencies of Glib package
env:
  UBUNTU_APT: ${{ 'libpango1.0-dev libglib2.0-dev libgdk-pixbuf2.0-dev gobject-introspection libcairo2-dev libatk1.0-dev glib-networking libgtk-3-dev libgirepository1.0-dev' }}

on:
  pull_request:
    branches: [ master ]
jobs:

  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift
      - name: Checkout testing repo
        uses: actions/checkout@v2
        with:
          repository: mikolasstuchlik/SwiftGtk
          path: SwiftGtk

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build gtk
        run: |
          cd SwiftGtk
          swift package update
          ../gir2swift/gir2swift-generation-driver.sh "$PWD" "$GIR2SWIFT_PATH"
          swift build -Xswiftc -suppress-warnings
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ../SwiftGtk
          swift package clean
          rm -rf .build/repositories
          cd ..
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-20.04-5.3
          path: |
            gir2swift/
            SwiftGtk/
          retention-days: 1
