name: Build gir2swift

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'libxml2 gobject-introspection' }}
  UBUNTU_APT: ${{ 'libxml2-dev gobject-introspection libgirepository1.0-dev' }}

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  # macOS tasks
  build-mac-swift-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.2'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-macos
          path: |
            gir2swift/
          retention-days: 1

  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-20.04-5.3
          path: |
            gir2swift/
          retention-days: 1

  # Ubuntu 18.04 tasks
  build-ubuntu-18_04-swift-latest:
    runs-on: ubuntu-18.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: |
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ..
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-18.04-5.3
          path: |
            gir2swift/
          retention-days: 1

  # Ubuntu 16.04 tasks
  build-ubuntu-16_04-swift-latest:
    runs-on: ubuntu-16.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout gir2swift
        uses: actions/checkout@v2
        with:
          path: gir2swift

      - name: Build current gir2swift
        run: |
          cd gir2swift
          ./build.sh
          echo "GIR2SWIFT_PATH=${PWD}/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: |
          cd gir2swift
          swift package clean
          rm -rf .build/repositories
          cd ..
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-16.04-5.3
          path: |
            gir2swift/
          retention-days: 1
